export const Color = {
  slate: "slate",
  gray: "gray",
  zinc: "zinc",
  neutral: "neutral",
  stone: "stone",
  red: "red",
  orange: "orange",
  amber: "amber",
  yellow: "yellow",
  lime: "lime",
  green: "green",
  teal: "teal",
  cyan: "cyan",
  blue: "blue",
  indigo: "indigo",
  purple: "purple",
  pink: "pink",
  brown: "brown",
  black: "black",
  white: "white",
}
